name: aiot
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - icu=78.2
  - ld_impl_linux-64=2.45
  - libexpat=2.7.3
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libsqlite=3.51.2
  - libstdcxx=15.2.0
  - libuuid=2.41.3
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - tk=8.6.13
  - tzdata=2025c
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - asttokens==3.0.1
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - debugpy==1.8.19
      - decorator==5.2.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.20.0
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - ipykernel==7.1.0
      - ipython==8.38.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mpmath==1.3.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - packaging==25.0
      - parso==0.8.5
      - pexpect==4.9.0
      - pillow==12.0.0
      - platformdirs==4.5.1
      - prompt-toolkit==3.0.52
      - psutil==7.2.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pygments==2.19.2
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pyzmq==27.1.0
      - six==1.17.0
      - stack-data==0.6.3
      - sympy==1.14.0
      - torch==2.9.1+cpu
      - torchaudio==2.9.1+cpu
      - torchvision==0.24.1+cpu
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.15.0
      - wcwidth==0.2.14
prefix: /home/esterique/miniconda3/envs/aiot
